spring:
  application:
    name: authorization-service
  cloud:
    vault:
      scheme: http
      uri: http://127.0.0.1:8200
      authentication: token
      token: ${VAULT_TOKEN}
      fail-fast: true
      kv:
        enabled: true
        backend: transit

